**Predicting the BankNote is genunine or not using deep learning**

In [ ]:
import tensorflow 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#read the dataset using pandas
data = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/bank_note_data/training_set_label.csv" )

In [3]:
data.head()

VWTI     SWTI     CWTI        EI  Class
0  2.2634  -4.4862   3.6558 -0.612510      0
1  3.2718   1.7837   2.1161  0.613340      0
2 -3.9411 -12.8792  13.0597 -3.312500      1
3  0.5195  -3.2633   3.0895 -0.984900      0
4  2.5698  -4.4076   5.9856  0.078002      0

In [4]:
data.shape

(1096, 5)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   VWTI    1096 non-null   float64
 1   SWTI    1096 non-null   float64
 2   CWTI    1096 non-null   float64
 3   EI      1096 non-null   float64
 4   Class   1096 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 42.9 KB


In [7]:
#Splitting independent and dependend vaiable
X=data.iloc[:,0:4]
y=data.iloc[:,-1]
print(X)


          VWTI     SWTI      CWTI        EI
0     2.263400  -4.4862   3.65580 -0.612510
1     3.271800   1.7837   2.11610  0.613340
2    -3.941100 -12.8792  13.05970 -3.312500
3     0.519500  -3.2633   3.08950 -0.984900
4     2.569800  -4.4076   5.98560  0.078002
...        ...      ...       ...       ...
1091  1.640600   3.5488   1.39640 -0.364240
1092 -0.048008  -1.6037   8.47560  0.755580
1093  2.942100   7.4101  -0.97709 -0.884060
1094  1.964700   6.9383   0.57722  0.663770
1095 -0.126240  10.3216  -3.71210 -6.118500

[1096 rows x 4 columns]


In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=101)

In [9]:
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [10]:
X_train.shape

(876, 4)

In [11]:
#initializing
model=Sequential()
model.add(Dense(10,activation='relu',input_dim=4))
model.add(Dense(1,activation='sigmoid'))
model.add(Dense(1))

In [12]:

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 2         
Total params: 63
Trainable params: 63
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [14]:
model.fit(X_train,y_train,epochs=30,batch_size=20)

Epoch 1/30
44/44 [==============================] - 0s 1ms/step - loss: 2.8118 - accuracy: 0.6084
Epoch 2/30
44/44 [==============================] - 0s 1ms/step - loss: 2.3283 - accuracy: 0.6530
Epoch 3/30
44/44 [==============================] - 0s 1ms/step - loss: 1.5781 - accuracy: 0.7089
Epoch 4/30
44/44 [==============================] - 0s 1ms/step - loss: 1.2259 - accuracy: 0.7500
Epoch 5/30
44/44 [==============================] - 0s 1ms/step - loss: 1.0164 - accuracy: 0.7865
Epoch 6/30
44/44 [==============================] - 0s 1ms/step - loss: 0.7526 - accuracy: 0.8139
Epoch 7/30
44/44 [==============================] - 0s 1ms/step - loss: 0.6256 - accuracy: 0.8368
Epoch 8/30
44/44 [==============================] - 0s 1ms/step - loss: 0.5732 - accuracy: 0.8562
Epoch 9/30
44/44 [==============================] - 0s 1ms/step - loss: 0.4173 - accuracy: 0.8721
Epoch 10/30
44/44 [==============================] - 0s 1ms/step - loss: 0.2852 - accuracy: 0.8893
Epoch 11/30
44/44 [

In [15]:
model.evaluate(X_test,y_test)

7/7 [==============================] - 0s 1ms/step - loss: 0.0238 - accuracy: 1.0000


[0.02381841093301773, 1.0]

In [16]:
#Prediction
y_pred=model.predict(X_test)

In [17]:
import math

In [18]:
y_pred

array([[ 6.55018270e-01],
       [-1.49910785e-02],
       [-1.41375829e-02],
       [-1.60257109e-02],
       [ 1.20187855e+00],
       [ 3.53194058e-01],
       [ 2.35667974e-02],
       [ 1.21541321e+00],
       [-1.62918270e-02],
       [-1.29575022e-02],
       [ 1.24208915e+00],
       [ 7.19815016e-01],
       [ 1.41356409e+00],
       [ 4.76496927e-02],
       [-1.35893831e-02],
       [-6.73078466e-03],
       [ 1.30770993e+00],
       [ 1.27795315e+00],
       [-1.51259247e-02],
       [ 1.16135478e+00],
       [ 1.04760218e+00],
       [ 1.36853683e+00],
       [ 6.95151389e-01],
       [-1.08755343e-02],
       [-1.09495549e-02],
       [ 3.46849710e-01],
       [ 1.26071966e+00],
       [-1.70831103e-02],
       [ 1.06068611e+00],
       [ 1.21220815e+00],
       [ 1.32204938e+00],
       [-1.05855344e-02],
       [ 1.41337097e+00],
       [ 1.37667871e+00],
       [-1.03964359e-02],
       [-1.47719234e-02],
       [ 1.35727060e+00],
       [ 6.75967336e-02],
       [-1.0

In [19]:
y_prediction=[]
for y_predi in y_pred:
  if y_predi>0.5:
    y_predi=1
    y_prediction.append(y_predi)
  else:
    y_predi=0
    y_prediction.append(y_predi)

In [20]:
y_pred=[]
for i in y_prediction:
  y_pred.append(i)
y_pred

[1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1]

In [21]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_prediction))

[[125   0]
 [  0  95]]


**Test data**

In [22]:
test_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/bank_note_data/testing_set_label.csv')
test_data.head()

VWTI      SWTI      CWTI       EI
0 -0.40804   0.54214  -0.52725  0.65860
1 -3.71810  -8.50890  12.36300 -0.95518
2  5.50400  10.36710  -4.41300 -4.02110
3  1.68490   8.74890  -1.26410 -1.38580
4  4.74320   2.10860   0.13680  1.65430

In [23]:
test=pd.DataFrame(test_data)
test.head()

VWTI      SWTI      CWTI       EI
0 -0.40804   0.54214  -0.52725  0.65860
1 -3.71810  -8.50890  12.36300 -0.95518
2  5.50400  10.36710  -4.41300 -4.02110
3  1.68490   8.74890  -1.26410 -1.38580
4  4.74320   2.10860   0.13680  1.65430

In [24]:
y_pred=model.predict(test)
y_pred

array([[ 1.04288721e+00],
       [ 1.32084799e+00],
       [-1.80555303e-02],
       [-1.62394531e-02],
       [-1.66545063e-02],
       [ 9.93093729e-01],
       [ 1.28953600e+00],
       [ 2.15861112e-01],
       [ 1.19014490e+00],
       [ 1.30481911e+00],
       [-6.81535993e-03],
       [ 1.00744390e+00],
       [-1.80809777e-02],
       [ 1.31033134e+00],
       [-1.78123135e-02],
       [ 6.52475655e-03],
       [-1.76012982e-02],
       [ 1.17219567e+00],
       [-1.78555176e-02],
       [ 1.33149266e+00],
       [ 1.35656333e+00],
       [ 1.17520070e+00],
       [-1.71952359e-02],
       [-1.67960618e-02],
       [-1.75764319e-02],
       [ 1.17543423e+00],
       [-1.58104040e-02],
       [-1.74927935e-02],
       [ 1.05927956e+00],
       [ 1.00274146e+00],
       [ 9.37472999e-01],
       [ 9.92559671e-01],
       [-1.79019421e-02],
       [-1.71208587e-02],
       [-1.57061927e-02],
       [ 1.21691966e+00],
       [ 1.22560716e+00],
       [-8.02115817e-03],
       [-3.5

In [25]:
y_test_prediction=[]
for y_predi in y_pred:
  if y_predi>0.5:
    y_predi=1
    y_test_prediction.append(y_predi)
  else:
    y_predi=0
    y_test_prediction.append(y_predi)


In [26]:
y_pred_test=[]
for i in y_test_prediction:
  y_pred_test.append(i)
y_pred_test

[1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,


In [27]:
submission =  pd.DataFrame({'Target':y_pred_test})
submission.head()

Target
0       1
1       1
2       0
3       0
4       0

In [28]:
submission.to_csv('submission.csv',index=False)